'use client'

import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { BookOpen, GraduationCap, Pencil, Plus, Save, X } from 'lucide-react'

type Content = { id?: string; content_type: 'objective'|'material'; title: string; body: string; image_url: string|null; display_order: number; show_in_briefing: boolean; is_active: boolean }
type Essay = { id?: string; question_code: string; story: string; answer_know: string; answer_asked: string; answer_plan: string; answer_solution: string; answer_check: string; score_weight: number; display_order: number; difficulty: string; operand_count:number; is_active: boolean }
const emptyContent: Content = { content_type:'material',title:'',body:'',image_url:null,display_order:0,show_in_briefing:true,is_active:true }
const emptyEssay: Essay = { question_code:'',story:'',answer_know:'',answer_asked:'',answer_plan:'',answer_solution:'',answer_check:'',score_weight:10,display_order:0,difficulty:'sedang',operand_count:2,is_active:true }

export function LearningManager() {
  const [contents,setContents]=useState<Content[]>([]), [essays,setEssays]=useState<Essay[]>([])
  const [content,setContent]=useState<Content|null>(null), [essay,setEssay]=useState<Essay|null>(null)
  const [error,setError]=useState(''), [saving,setSaving]=useState(false)
  const load=useCallback(()=>fetch('/api/admin/learning',{cache:'no-store'}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error);setContents(v.data.contents);setEssays(v.data.essays)}).catch(e=>setError(e.message)),[])
  useEffect(()=>{void load()},[load])
  async function save(event:FormEvent, entity:'content'|'essay') { event.preventDefault();setSaving(true);setError('');try{const payload=entity==='content'?content:essay;const response=await fetch('/api/admin/learning',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity,...payload})});const result=await response.json();if(!response.ok)throw new Error(result.error);setContent(null);setEssay(null);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan')}finally{setSaving(false)} }
  async function deactivate(entity:'content'|'essay',id?:string){if(!id||!confirm('Nonaktifkan item ini?'))return;const r=await fetch(`/api/admin/learning?entity=${entity}&id=${id}`,{method:'DELETE'});if(r.ok)await load()}
  return <div className="admin-learning-stack">
    {error&&<div className="admin-alert error">{error}</div>}
    <section className="admin-panel"><div className="admin-panel-title"><div><span className="admin-kicker">KONTEN AWAL</span><h2>Tujuan pembelajaran & materi</h2></div><button className="admin-primary-button" onClick={()=>setContent({...emptyContent})}><Plus/>Tambah materi</button></div>
      <div className="admin-content-cards">{contents.map(item=><article key={item.id} className={!item.is_active?'inactive':''}><div className="admin-content-icon">{item.content_type==='objective'?<GraduationCap/>:<BookOpen/>}</div><div><small>{item.content_type==='objective'?'TUJUAN PEMBELAJARAN':'MATERI'}</small><strong>{item.title}</strong><p>{item.body}</p></div><button onClick={()=>setContent({...item})}><Pencil/></button><button onClick={()=>deactivate('content',item.id)}><X/></button></article>)}</div>
    </section>
    {content&&<form className="admin-form-section" onSubmit={e=>save(e,'content')}><div className="admin-form-section-heading"><span>TP</span><div><h2>{content.id?'Ubah konten':'Tambah konten'}</h2><p>Konten aktif ditampilkan pada halaman pembuka siswa.</p></div></div><div className="admin-form-grid two"><label>Jenis<select value={content.content_type} onChange={e=>setContent({...content,content_type:e.target.value as Content['content_type']})}><option value="objective">Tujuan Pembelajaran</option><option value="material">Materi</option></select></label><label>Urutan<input type="number" value={content.display_order} onChange={e=>setContent({...content,display_order:Number(e.target.value)})}/></label></div><label>Judul<input required value={content.title} onChange={e=>setContent({...content,title:e.target.value})}/></label><label>Isi<textarea required rows={6} value={content.body} onChange={e=>setContent({...content,body:e.target.value})}/></label><label>URL gambar (opsional)<input value={content.image_url||''} onChange={e=>setContent({...content,image_url:e.target.value})}/></label>{content.content_type==='material'&&<label className="admin-switch-row"><input type="checkbox" checked={content.show_in_briefing} onChange={e=>setContent({...content,show_in_briefing:e.target.checked})}/><span><strong>Tampilkan pada ringkasan sebelum game</strong><small>Materi lengkap tetap tersedia pada halaman Materi.</small></span></label>}<div className="admin-form-actions"><button type="button" className="admin-secondary-button" onClick={()=>setContent(null)}>Batal</button><button className="admin-primary-button" disabled={saving}><Save/>{saving?'Menyimpan...':'Simpan'}</button></div></form>}
    <section className="admin-panel"><div className="admin-panel-title"><div><span className="admin-kicker">FASE 1</span><h2>Bank soal uraian</h2></div><button className="admin-primary-button" onClick={()=>setEssay({...emptyEssay})}><Plus/>Tambah uraian</button></div><div className="admin-essay-list">{essays.map(item=><article key={item.id} className={!item.is_active?'inactive':''}><span>{item.question_code}</span><div><strong>{item.story}</strong><small>Bobot {item.score_weight} · urutan {item.display_order}</small></div><button onClick={()=>setEssay({...item})}><Pencil/></button><button onClick={()=>deactivate('essay',item.id)}><X/></button></article>)}</div></section>
    {essay&&<form className="admin-question-form" onSubmit={e=>save(e,'essay')}><section className="admin-form-section"><div className="admin-form-section-heading"><span>U</span><div><h2>{essay.id?'Ubah soal uraian':'Tambah soal uraian'}</h2><p>Simpan acuan empat tahap Polya untuk membantu koreksi manual.</p></div></div><div className="admin-form-grid four"><label>Kode<input required value={essay.question_code} onChange={e=>setEssay({...essay,question_code:e.target.value.toUpperCase()})}/></label><label>Kesulitan<select value={essay.difficulty} onChange={e=>setEssay({...essay,difficulty:e.target.value})}><option value="mudah">Mudah</option><option value="sedang">Sedang</option><option value="hots">HOTS</option></select></label><label>Jumlah bilangan<select value={essay.operand_count} onChange={e=>setEssay({...essay,operand_count:Number(e.target.value)})}><option value={2}>Dua bilangan</option><option value={3}>Tiga bilangan</option></select></label><label>Urutan<input type="number" value={essay.display_order} onChange={e=>setEssay({...essay,display_order:Number(e.target.value)})}/></label></div><label>Teks soal<textarea required rows={4} value={essay.story} onChange={e=>setEssay({...essay,story:e.target.value})}/></label><div className="admin-form-grid two">{([['answer_know','Tahap 1 · Acuan Diketahui'],['answer_asked','Tahap 1 · Acuan Ditanyakan'],['answer_plan','Tahap 2 · Acuan Rencana Pemecahan'],['answer_solution','Tahap 3 · Acuan Pelaksanaan Rencana'],['answer_check','Tahap 4 · Acuan Pemeriksaan Kembali']] as const).map(([key,label])=><label key={key}>{label}<textarea rows={4} value={essay[key]||''} onChange={e=>setEssay({...essay,[key]:e.target.value})}/></label>)}</div><div className="admin-form-actions"><button type="button" className="admin-secondary-button" onClick={()=>setEssay(null)}>Batal</button><button className="admin-primary-button" disabled={saving}><Save/>{saving?'Menyimpan...':'Simpan soal'}</button></div></section></form>}
  </div>
}
