'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, BookOpenCheck, Gamepad2, Sparkles, Target } from 'lucide-react'

type Essay = { id:string; known_answer:string; asked_answer:string; plan_answer:string; solution_answer:string; check_answer:string; solution_method:string|null; known_score:number|null; asked_score:number|null; understanding_score:number|null; planning_score:number|null; execution_score:number|null; review_score:number|null; manual_score:number|null; questions:{question_code:string;story:string;score_weight:number}|Array<{question_code:string;story:string;score_weight:number}>|null }
type Detail = { profile:{name:string;attendance_number:string|null;total_xp:number;level:number;total_score:number}; totals:{sessions:number;answers:number;accuracy:number;pgScore:number;essayScore:number;finalScore:number|null;status:string}; indicators:{pretest:number;information:number;strategy:number;kpk:number;verification:number}; rooms:Array<{room_id:string;score:number;correct_answers:number;wrong_answers:number;joined_at:string;rooms:{room_code:string}|Array<{room_code:string}>|null}>; essays:Essay[] }

function Indicator({ label, value }:{label:string;value:number}) { return <div className="admin-indicator"><div><strong>{label}</strong><span className={value>=75?'achieved':'needs-work'}>{value}% {value>=75?'✓':'!'}</span></div><div className="admin-progress"><span className={value>=75?'achieved':'needs-work'} style={{width:`${value}%`}}/></div></div> }

function StageGrade({ answer, max }:{answer:Essay;max:number}) {
  const [scores, setScores] = useState({ knownScore:answer.known_score ?? 0, askedScore:answer.asked_score ?? 0, planningScore:answer.planning_score ?? 0, executionScore:answer.execution_score ?? 0, reviewScore:answer.review_score ?? 0 })
  const [saved, setSaved] = useState(answer.manual_score !== null)
  const fields = [['knownScore','Diketahui',1],['askedScore','Ditanyakan',1],['planningScore','Merencanakan',2],['executionScore','Melaksanakan',4],['reviewScore','Memeriksa',2]] as const
  async function save() { const response=await fetch(`/api/admin/essay-answers/${answer.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(scores)}); if(response.ok)setSaved(true) }
  return <div className="essay-stage-grade">{fields.map(([key,label,partMax])=><label key={key}><span>{label}</span><input aria-label={`Nilai ${label}`} type="number" min="0" max={partMax} value={scores[key]} onChange={event=>{setScores(current=>({...current,[key]:Number(event.target.value)}));setSaved(false)}}/><small>/ {partMax}</small></label>)}<div><b>Total {Object.values(scores).reduce((sum,value)=>sum+value,0)} / {max}</b><button onClick={save}>{saved?'Tersimpan':'Simpan nilai'}</button></div></div>
}

function EssayReview({ answers }:{answers:Essay[]}) { return <section className="admin-panel admin-essay-review"><div className="admin-panel-title"><div><span className="admin-kicker">JAWABAN URAIAN</span><h2>Empat tahap pemecahan masalah</h2></div><span>{answers.length} jawaban</span></div>{answers.length===0?<p>Belum ada jawaban uraian.</p>:answers.map(answer=>{const question=Array.isArray(answer.questions)?answer.questions[0]:answer.questions;return <article key={answer.id}><header><strong>{question?.question_code} · {question?.story}</strong></header><div className="essay-stage-answers"><section><b>01 · Memahami masalah</b><p><strong>Diketahui</strong>{answer.known_answer}</p><p><strong>Ditanyakan</strong>{answer.asked_answer}</p></section><p><b>02 · Merencanakan pemecahan</b>{answer.plan_answer}</p><p><b>03 · Melaksanakan rencana</b>{answer.solution_answer}</p><p><b>04 · Memeriksa kembali</b>{answer.check_answer}</p></div><StageGrade answer={answer} max={question?.score_weight||10}/></article>})}</section> }

export function StudentDetail({ studentId }:{studentId:string}) {
  const [detail,setDetail]=useState<Detail|null>(null), [error,setError]=useState('')
  useEffect(()=>{fetch(`/api/admin/reports/students/${studentId}`).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error||'Gagal memuat detail murid');setDetail(value.data)}).catch(cause=>setError(cause instanceof Error?cause.message:'Gagal memuat detail murid'))},[studentId])
  if(error)return <div className="admin-alert error">{error}</div>
  if(!detail)return <section className="admin-panel admin-form-loading">Memuat detail murid...</section>
  const essays=detail.essays||[]
  return <><Link href="/admin/reports" className="admin-secondary-button admin-back-link"><ArrowLeft/>Kembali ke rekap</Link><section className="admin-student-hero"><div className="admin-avatar large">{detail.profile.name[0]}</div><div><span className="admin-kicker">PROFIL MURID · ABSEN {detail.profile.attendance_number||'--'}</span><h1>{detail.profile.name}</h1><p>Level {detail.profile.level} · {detail.profile.total_xp} XP · {detail.profile.total_score} total poin</p></div></section><section className="admin-metric-grid student-metrics"><article className="admin-metric blue"><div className="admin-metric-icon"><Gamepad2/></div><div><span>Nilai PG</span><strong>{detail.totals.pgScore}/50</strong></div></article><article className="admin-metric green"><div className="admin-metric-icon"><BookOpenCheck/></div><div><span>Nilai Uraian</span><strong>{detail.totals.essayScore}/50</strong></div></article><article className="admin-metric amber"><div className="admin-metric-icon"><Target/></div><div><span>Nilai Akhir</span><strong>{detail.totals.finalScore??'—'}</strong><small>{detail.totals.status}</small></div></article></section><section className="admin-dashboard-grid student-detail-grid"><article className="admin-panel"><div className="admin-panel-title"><div><span className="admin-kicker">TUJUAN PEMBELAJARAN</span><h2>Ketercapaian indikator</h2></div><Sparkles/></div><div className="admin-indicator-list"><Indicator label="Pretest prasyarat" value={detail.indicators.pretest}/><Indicator label="Memahami informasi" value={detail.indicators.information}/><Indicator label="Menentukan strategi" value={detail.indicators.strategy}/><Indicator label="Menghitung KPK" value={detail.indicators.kpk}/><Indicator label="Memeriksa jawaban" value={detail.indicators.verification}/></div></article><article className="admin-panel"><div className="admin-panel-title"><div><span className="admin-kicker">RIWAYAT</span><h2>Sesi terbaru</h2></div></div><div className="admin-session-list">{detail.rooms.length===0?<p>Belum ada sesi permainan.</p>:detail.rooms.slice(0,8).map(room=>{const relation=Array.isArray(room.rooms)?room.rooms[0]:room.rooms;return <div key={`${room.room_id}-${room.joined_at}`}><span><strong>{relation?.room_code||'Room'}</strong><small>{new Date(room.joined_at).toLocaleDateString('id-ID')}</small></span><span><strong>{room.score} poin</strong><small>{room.correct_answers} benar · {room.wrong_answers} belum tepat</small></span></div>})}</div></article></section><EssayReview answers={essays}/></>
}
